services:
  db:
    image: postgres:13
    container_name: ratpi_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ratpi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/01_init_database.sql:/docker-entrypoint-initdb.d/01_init_database.sql
      - ./src/02_data.sql:/docker-entrypoint-initdb.d/02_data.sql
volumes:
  postgres_data:
